{
  parserClass="com.github.juggernaut0.snek.parser.SnekParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Snek"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.juggernaut0.snek.psi"
  psiImplPackage="com.github.juggernaut0.snek.psi.impl"

  elementTypeHolderClass="com.github.juggernaut0.snek.psi.SnekTypes"
  elementTypeClass="com.github.juggernaut0.snek.psi.SnekElementType"
  tokenTypeClass="com.github.juggernaut0.snek.psi.SnekTokenType"
}

snekFile ::= decl*

decl ::= COMMENT | binding | call_expr {recoverWhile=recover}
private recover ::= !(PUBLIC | LET | L_PAREN)

binding ::= PUBLIC? LET pattern EQUALS expr {pin=2}

pattern ::= IDENT

expr ::= STRING | IDENT | call_expr
call_expr ::= L_PAREN expr+ R_PAREN {pin=1}
